### ISSUE TITLE
Build fails in the CI when running .ci/scripts/test.sh for "packages/rum-angular"

### ISSUE THREAD

**Issue by v1v** [elastic/apm-agent-rum-js#1036]
### What
`Run tests: Elastic Stack 8.0.0-SNAPSHOT - @elastic/apm-rum-angular - none` is failing in the CI

Build logs -> https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-rum%2Fapm-agent-rum-mbp/detail/master/413/pipeline/658#step-1266-log-95

### Logs

See https://apm-ci.elastic.co/job/apm-agent-rum/job/apm-agent-rum-mbp/job/master/413/execution/node/1266/log/

```
17:37:58  node-puppeteer         | > node ../../dev-utils/run-script.js "runSauceTests" "packages/rum-angular" "true" "test:unit" "build:e2e" "test:e2e"
17:37:59  node-puppeteer         | internal/modules/cjs/loader.js:818
17:37:59  node-puppeteer         |   throw err;
17:37:59  node-puppeteer         |   ^
17:37:59  node-puppeteer         | Error: Cannot find module 'puppeteer'
17:37:59  node-puppeteer         | Require stack:
17:37:59  node-puppeteer         | - /app/dev-utils/integration-test.js
17:37:59  node-puppeteer         | - /app/dev-utils/test-servers.js
17:37:59  node-puppeteer         | - /app/dev-utils/run-script.js
17:37:59  node-puppeteer         |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
17:37:59  node-puppeteer         |     at Function.Module._load (internal/modules/cjs/loader.js:667:27)
17:37:59  node-puppeteer         |     at Module.require (internal/modules/cjs/loader.js:887:19)
17:37:59  node-puppeteer         |     at require (internal/modules/cjs/helpers.js:74:18)
17:37:59  node-puppeteer         |     at Object.<anonymous> (/app/dev-utils/integration-test.js:26:19)
17:37:59  node-puppeteer         |     at Module._compile (internal/modules/cjs/loader.js:999:30)
17:37:59  node-puppeteer         |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
17:37:59  node-puppeteer         |     at Module.load (internal/modules/cjs/loader.js:863:32)
17:37:59  node-puppeteer         |     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
17:37:59  node-puppeteer         |     at Module.require (internal/modules/cjs/loader.js:887:19) {
17:37:59  node-puppeteer         |   code: 'MODULE_NOT_FOUND',
17:37:59  node-puppeteer         |   requireStack: [
17:37:59  node-puppeteer         |     '/app/dev-utils/integration-test.js',
17:37:59  node-puppeteer         |     '/app/dev-utils/test-servers.js',
17:37:59  node-puppeteer         |     '/app/dev-utils/run-script.js'
17:37:59  node-puppeteer         |   ]
17:37:59  node-puppeteer         | }
17:37:59  node-puppeteer         | npm ERR! code ELIFECYCLE
17:37:59  node-puppeteer         | npm ERR! errno 1
17:37:59  node-puppeteer         | npm ERR! @elastic/apm-rum-angular@2.0.1 script: `node ../../dev-utils/run-script.js "runSauceTests" "packages/rum-angular" "true" "test:unit" "build:e2e" "test:e2e"`
17:37:59  node-puppeteer         | npm ERR! Exit status 1
17:37:59  node-puppeteer         | npm ERR! 
17:37:59  node-puppeteer         | npm ERR! Failed at the @elastic/apm-rum-angular@2.0.1 script script.
17:37:59  node-puppeteer         | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
17:37:59  node-puppeteer         | npm ERR! A complete log of this run can be found in:
17:37:59  node-puppeteer         | npm ERR!     /app/.npm/_logs/2021-06-08T16_37_59_648Z-debug.log
17:37:59  node-puppeteer         | npm ERR! code ELIFECYCLE
17:37:59  node-puppeteer         | npm ERR! errno 1
17:37:59  node-puppeteer         | npm ERR! @elastic/apm-rum-angular@2.0.1 test:sauce: `npm run script runSauceTests packages/rum-angular true test:unit build:e2e test:e2e`
17:37:59  node-puppeteer         | npm ERR! Exit status 1
```

**Comment by vigneshshanmugam** [comment]
This was an interim issue, probably the fetcher endpoint was down, 
```
 ERROR: Failed to download Chromium r686378! Set "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD" env variable to skip download.
[2021-06-08T16:37:17.060Z] node-puppeteer         | Error: end of central directory record signature not found
[2021-06-08T16:37:17.060Z] node-puppeteer         |     at /app/node_modules/extract-zip/node_modules/yauzl/index.js:187:14
[2021-06-08T16:37:17.060Z] node-puppeteer         |     at /app/node_modules/extract-zip/node_modules/yauzl/index.js:631:5
[2021-06-08T16:37:17.060Z] node-puppeteer         |     at /app/node_modules/extract-zip/node_modules/fd-slicer/index.js:32:7
[2021-06-08T16:37:17.060Z] node-puppeteer         |     at FSReqCallback.wrapper [as oncomplete] (fs.js:520:5)
[2021-06-08T16:37:17.060Z] node-puppeteer         |   -- ASYNC --
[2021-06-08T16:37:17.060Z] node-puppeteer         |     at BrowserFetcher.<anonymous> (/app/node_modules/puppeteer/lib/helper.js:111:15)
[2021-06-08T16:37:17.060Z] node-puppeteer         |     at Object.<anonymous> (/app/node_modules/puppeteer/install.js:64:16)
[2021-06-08T16:37:17.060Z] node-puppeteer         |     at Module._compile (internal/modules/cjs/loader.js:999:30)
[2021-06-08T16:37:17.060Z] node-puppeteer         |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
[2021-06-08T16:37:17.060Z] node-puppeteer         |     at Module.load (internal/modules/cjs/loader.js:863:32)
[2021-06-08T16:37:17.060Z] node-puppeteer         |     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
[2021-06-08T16:37:17.060Z] node-puppeteer         |     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
[2021-06-08T16:37:17.061Z] node-puppeteer         |     at internal/main/run_main_module.js:17:47

```

Retrying it fixed it though and test did pass after that. Closing the issue, let us reopen if it starts to be unreliable.
