### ISSUE TITLE
RUM agent master branch test failing on missing dependencies

### ISSUE THREAD

**Issue by cachedout** [elastic/apm-agent-rum-js#1072]
We are seeing a failures in the master branch which [appear to the result of missing dependencies](https://apm-ci.elastic.co/blue/rest/organizations/jenkins/pipelines/apm-agent-rum/pipelines/apm-agent-rum-mbp/branches/master/runs/431/nodes/2339/steps/2458/log/?start=0):

```
[2021-08-13T16:56:10.686Z] node-playwright        | @elastic/apm-rum: Server listening at http://localhost:9000
[2021-08-13T16:56:21.621Z] node-playwright        | @elastic/apm-rum: Error running RUM benchmark script browserType.launch: 
[2021-08-13T16:56:21.621Z] node-playwright        | @elastic/apm-rum: ╔════════════════════════════════════════════════════════════╗
[2021-08-13T16:56:21.621Z] node-playwright        | @elastic/apm-rum: ║ Host system is missing a few dependencies to run browsers. ║
[2021-08-13T16:56:21.621Z] node-playwright        | @elastic/apm-rum: ║ Please install them with the following command:            ║
[2021-08-13T16:56:21.621Z] node-playwright        | @elastic/apm-rum: ║                                                            ║
[2021-08-13T16:56:21.621Z] node-playwright        | @elastic/apm-rum: ║     sudo npx playwright install-deps                       ║
[2021-08-13T16:56:21.621Z] node-playwright        | @elastic/apm-rum: ║                                                            ║
[2021-08-13T16:56:21.621Z] node-playwright        | @elastic/apm-rum: ║ <3 Playwright Team                                         ║
[2021-08-13T16:56:21.621Z] node-playwright        | @elastic/apm-rum: ╚════════════════════════════════════════════════════════════╝
[2021-08-13T16:56:21.621Z] node-playwright        | @elastic/apm-rum:     at launchBrowser (/app/packages/rum/test/benchmarks/profiler.js:36:33)
[2021-08-13T16:56:21.621Z] node-playwright        | @elastic/apm-rum:     at run (/app/packages/rum/test/benchmarks/run.js:75:33) {
[2021-08-13T16:56:21.621Z] node-playwright        | @elastic/apm-rum:   name: 'Error'
[2021-08-13T16:56:21.621Z] node-playwright        | @elastic/apm-rum: }
[2021-08-13T16:56:21.621Z] node-playwright        | @elastic/apm-rum: npm ERR! code ELIFECYCLE
[2021-08-13T16:56:21.621Z] node-playwright        | @elastic/apm-rum: npm ERR! errno 1
[2021-08-13T16:56:21.622Z] node-playwright        | @elastic/apm-rum: npm ERR! @elastic/apm-rum@5.9.1 bench: `npm run build:umd && node test/benchmarks/run.js`
[2021-08-13T16:56:21.622Z] node-playwright        | @elastic/apm-rum: npm ERR! Exit status 1
[2021-08-13T16:56:21.622Z] node-playwright        | @elastic/apm-rum: npm ERR! 
[2021-08-13T16:56:21.622Z] node-playwright        | @elastic/apm-rum: npm ERR! Failed at the @elastic/apm-rum@5.9.1 bench script.
[2021-08-13T16:56:21.622Z] node-playwright        | @elastic/apm-rum: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[2021-08-13T16:56:21.622Z] node-playwright        | @elastic/apm-rum: npm WARN Local package.json exists, but node_modules missing, did you mean to install?
[2021-08-13T16:56:21.622Z] node-playwright        | @elastic/apm-rum: npm ERR! A complete log of this run can be found in:
[2021-08-13T16:56:21.622Z] node-playwright        | @elastic/apm-rum: npm ERR!     /app/.npm/_logs/2021-08-13T16_56_21_190Z-debug.log
[2021-08-13T16:56:21.622Z] node-playwright        | lerna ERR! npm run bench exited 1 in '@elastic/apm-rum'
[2021-08-13T16:56:22.320Z] node-playwright exited with code 1
```

**Comment by vigneshshanmugam** [comment]
@cachedout I will have a look today. Thanks for the headsup.
