### ISSUE TITLE
Cannot read properties of undefined (reading 'fetchStart')

### ISSUE THREAD

**Issue by kanadaj** [elastic/apm-agent-rum-js#1104]
After deploying RUM, I don't seem to get data from some users. Got their data in Sentry though, so here it is:

### Browser
name | Chrome
-- | --
version | 96.0.4664

### OS
Name | Windows
-- | --
Version | 10

### SDK
Name | @elastic/apm-rum
-- | --
Version | 5.9.1

### Stacktrace
```ts
TypeError: Cannot read properties of undefined (reading 'fetchStart')
  at ? (./node_modules/@elastic/apm-rum-core/dist/es/common/compress.js:115:27)
  at Array.forEach(<anonymous>)
  at compressMarks(./node_modules/@elastic/apm-rum-core/dist/es/common/compress.js:113:31)
  at compressTransaction(./node_modules/@elastic/apm-rum-core/dist/es/common/compress.js:195:8)
  at ? (./node_modules/@elastic/apm-rum-core/dist/es/common/apm-server.js:313:94)
  at Array.map(<anonymous>)
  at ndjsonTransactions(./node_modules/@elastic/apm-rum-core/dist/es/common/apm-server.js:291:25)
  at sendEvents(./node_modules/@elastic/apm-rum-core/dist/es/common/apm-server.js:359:87)
  at onFlush(./node_modules/@elastic/apm-rum-core/dist/es/common/apm-server.js:33:27)
  at flush(./node_modules/@elastic/apm-rum-core/dist/es/common/queue.js:34:10)
  at apply(./node_modules/@elastic/apm-rum-core/dist/es/common/queue.js:20:20)
  at r(./node_modules/@sentry/browser/esm/helpers.js:72:23)
```

It seems to work for most users, and not for some others.

**Comment by kanadaj** [comment]
To add a bit, I think it may be an issue caused by ads loading stuff in in the background, causing an issue with working out the end of the span? Not really sure though.

**Comment by vigneshshanmugam** [comment]
Its strange how this could happen unless the transaction object is modified and the transaction marks are removed somewhere else in the code. Do you have any logic to change the transaction object through these API? https://www.elastic.co/guide/en/apm/agent/rum-js/current/agent-api.html#apm-add-filter.

We can always add a null check for navigationTiming here - https://github.com/elastic/apm-agent-rum-js/blob/07544e8fd1585430b192bd127c9c70cc1237ee52/packages/rum-core/src/common/compress.js#L123.

Can you help debug this? 

1. Can you reproduce this on any of your environments? If yes, can you check if the navigation timing object is modified `window.performance.timing`
2. Does it work when you disable the ads? 
3. Are you loading RUM agent in the main window or iframes?

**Comment by vigneshshanmugam** [comment]
@devcorpio was able to reproduce this behaviour and the reason was due to the transactions that are not page-load. This seems to be a bug in the rum agent. Thanks for bringing this to our notice.

**Comment by kanadaj** [comment]
Ah sorry, only saw your reply just now, sorry about the lack of a reply! Thankfully you were able to reproduce, I found it hard to repro it reliably at all. Please LMK once this is fixed, atm it makes me unable to gather data from a subset of users.

**Comment by devcorpio** [comment]
Hi @kanadaj a new [release](https://github.com/elastic/apm-agent-rum-js/blob/master/CHANGELOG.asciidoc) with the fix is available.
