### ISSUE TITLE
Bechmark stage in the CI is failing 

### ISSUE THREAD

**Issue by v1v** [elastic/apm-agent-rum-js#1178]
Last known successful build was [11-Feb-2022](https://apm-ci.elastic.co/job/apm-agent-rum/job/apm-agent-rum-mbp/job/main/20/).

Then from [14-Feb-2022](https://apm-ci.elastic.co/job/apm-agent-rum/job/apm-agent-rum-mbp/job/main/21/) started to fail

```
[2022-02-14T19:55:53.501Z] [36mnode-playwright        |[0m @elastic/apm-rum: This can impact web performance.
[2022-02-14T19:55:53.501Z] [36mnode-playwright        |[0m @elastic/apm-rum: Assets: 
[2022-02-14T19:55:53.501Z] [36mnode-playwright        |[0m @elastic/apm-rum:   elastic-apm-opentracing.umd.min.js (66 KiB)[39m[22m
[2022-02-14T19:55:53.501Z] [36mnode-playwright        |[0m @elastic/apm-rum: [1m[33mWARNING[39m[22m in [1mwebpack performance recommendations: 
[2022-02-14T19:55:53.501Z] [36mnode-playwright        |[0m @elastic/apm-rum: You can limit the size of your bundles by using import() or require.ensure to lazy load some parts of your application.
[2022-02-14T19:55:53.501Z] [36mnode-playwright        |[0m @elastic/apm-rum: For more info visit https://webpack.js.org/guides/code-splitting/[39m[22m
[2022-02-14T19:55:53.501Z] [36mnode-playwright        |[0m @elastic/apm-rum: webpack 5.38.1 compiled with [1m[33m2 warnings[39m[22m in 9963 ms
[2022-02-14T19:55:58.663Z] [36mnode-playwright        |[0m @elastic/apm-rum: custom apm build -  apm-rum-with-name.umd.min.js generated
[2022-02-14T19:55:58.663Z] [36mnode-playwright        |[0m @elastic/apm-rum: Server listening at http://localhost:9000
[2022-02-14T19:56:00.919Z] [36mnode-playwright        |[0m @elastic/apm-rum: Error running RUM benchmark script browserType.launch: 
[2022-02-14T19:56:00.919Z] [36mnode-playwright        |[0m @elastic/apm-rum: ╔════════════════════════════════════════════════════════════╗
[2022-02-14T19:56:00.919Z] [36mnode-playwright        |[0m @elastic/apm-rum: ║ Host system is missing a few dependencies to run browsers. ║
[2022-02-14T19:56:00.919Z] [36mnode-playwright        |[0m @elastic/apm-rum: ║ Please install them with the following command:            ║
[2022-02-14T19:56:00.919Z] [36mnode-playwright        |[0m @elastic/apm-rum: ║                                                            ║
[2022-02-14T19:56:00.919Z] [36mnode-playwright        |[0m @elastic/apm-rum: ║     sudo npx playwright install-deps                       ║
[2022-02-14T19:56:00.919Z] [36mnode-playwright        |[0m @elastic/apm-rum: ║                                                            ║
[2022-02-14T19:56:00.919Z] [36mnode-playwright        |[0m @elastic/apm-rum: ║ <3 Playwright Team                                         ║
[2022-02-14T19:56:00.919Z] [36mnode-playwright        |[0m @elastic/apm-rum: ╚════════════════════════════════════════════════════════════╝
[2022-02-14T19:56:00.919Z] [36mnode-playwright        |[0m @elastic/apm-rum:     at launchBrowser (/app/packages/rum/test/benchmarks/profiler.js:36:33)
[2022-02-14T19:56:00.919Z] [36mnode-playwright        |[0m @elastic/apm-rum:     at run (/app/packages/rum/test/benchmarks/run.js:75:33) {
[2022-02-14T19:56:00.919Z] [36mnode-playwright        |[0m @elastic/apm-rum:   name: 'Error'
[2022-02-14T19:56:00.919Z] [36mnode-playwright        |[0m @elastic/apm-rum: }
[2022-02-14T19:56:01.619Z] [36mnode-playwright        |[0m @elastic/apm-rum: npm ERR! code ELIFECYCLE
[2022-02-14T19:56:01.619Z] [36mnode-playwright        |[0m @elastic/apm-rum: npm ERR! errno 1
[2022-02-14T19:56:01.619Z] [36mnode-playwright        |[0m @elastic/apm-rum: npm ERR! @elastic/apm-rum@5.10.2 bench: `npm run build:umd && node test/benchmarks/run.js`
[2022-02-14T19:56:01.619Z] [36mnode-playwright        |[0m @elastic/apm-rum: npm ERR! Exit status 1
[2022-02-14T19:56:01.619Z] [36mnode-playwright        |[0m @elastic/apm-rum: npm ERR! 
[2022-02-14T19:56:01.619Z] [36mnode-playwright        |[0m @elastic/apm-rum: npm ERR! Failed at the @elastic/apm-rum@5.10.2 bench script.
[2022-02-14T19:56:01.619Z] [36mnode-playwright        |[0m @elastic/apm-rum: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[2022-02-14T19:56:01.619Z] [36mnode-playwright        |[0m @elastic/apm-rum: npm WARN Local package.json exists, but node_modules missing, did you mean to install?
[2022-02-14T19:56:01.619Z] [36mnode-playwright        |[0m @elastic/apm-rum: npm ERR! A complete log of this run can be found in:
[2022-02-14T19:56:01.619Z] [36mnode-playwright        |[0m @elastic/apm-rum: npm ERR!     /app/.npm/_logs/2022-02-14T19_56_00_880Z-debug.log
[2022-02-14T19:56:01.619Z] [36mnode-playwright        |[0m lerna ERR! npm run bench exited 1 in '@elastic/apm-rum'
[2022-02-14T19:56:01.619Z] [36mnode-playwright exited with code 1
[2022-02-14T19:56:01.619Z] [0mAborting on container exit...
```

The entire log can be seen [here](https://apm-ci.elastic.co/blue/rest/organizations/jenkins/pipelines/apm-agent-rum/pipelines/apm-agent-rum-mbp/branches/main/runs/21/nodes/1842/log/?start=0)

What command did it run in the CI? `./.ci/scripts/benchmarks.sh`

**Comment by devcorpio** [comment]
@v1v,

Unfortunately the issue is not related at all with the **ajv** change. And that's the only change we made back then. 

Is it possible this issue comes for a change in the jenkins infrastructure? Another thing I can do is to check logs and see if different versions of any software are different since February 14th.

I executed the benchmarks locally and worked properly. But it's true that I tested locally using `npx lerna run bench `rather than using `./.ci/scripts/benchmarks.sh`, but when it comes to the javascript code there are not differences.

When executing the ci script locally I received this in my **arm** mac:

```
#8 2.159 Preparing to unpack .../wget_1.19.4-1ubuntu2.2_arm64.deb ...
#8 2.162 Unpacking wget (1.19.4-1ubuntu2.2) ...
#8 2.214 Setting up wget (1.19.4-1ubuntu2.2) ...
#8 2.308 Warning: apt-key output should not be parsed (stdout is not a terminal)
#8 2.734 OK
#8 4.747 E: Unable to locate package google-chrome-unstable
```

**Comment by devcorpio** [comment]
Okay, the last known successful build was using playwright [1.8.1](https://github.com/microsoft/playwright/releases/tag/v1.18.1)

Since February 14th the CI started to use playwright [1.9.1](https://github.com/microsoft/playwright/releases/tag/v1.19.1) which uses a new version of Firefox.

In our [DockerFile](https://github.com/elastic/apm-agent-rum-js/blob/main/.ci/docker/node-playwright/Dockerfile#L19) a new dependency (**[libxtst6](https://github.com/microsoft/playwright-python/issues/1169)**) is needed in order to solve the issue with Firefox.

PR is coming

cc: @vigneshshanmugam
