### ISSUE TITLE
User experience events seeing 400 after enabling distributed tracing

### ISSUE THREAD

**Issue by abhinavsingh** [elastic/apm-agent-rum-js#1536]
Hi,

Ever since we enabled distributed tracing options, we have started seeing these errors for every first event sent to rum endpoint.   Subsequent events work fine.

Looks like there is an issue when sending UX (user experience) events when distributed tracing is enabled.   We were able to verify the same via UX dashboard.   It stopped seeing the events once we enabled distributed tracing.

```
app.js:50128 [Elastic APM] Failed sending events! Error: https://apm.cube.jaxl.run/intake/v2/rum/events HTTP status: 400 decode error: data read error: v2.transactionRoot.Transaction: v2.transaction.Sampled: ReadBool: expect t or f,
    at e._constructError (app.js:175:12)
    at app.js:99:70
```

We are using `"@elastic/apm-rum": "^5.16.0"`.

Any workaround for it?

**Comment by Gummba** [comment]
Similar problem. We had:

```js
;(function(d, s, c) 
{
    var j = d.createElement(s),
      t = d.getElementsByTagName(s)[0]

    j.src = 'js/elastic-apm-rum.umd.min.js'
    j.onload = function() {elasticApm.init(c)}
    t.parentNode.insertBefore(j, t)
})
(
  document
  , 'script'
  , {
      serviceName: $scope.myInfo.elastic_apm_service_name
      , serverUrl: $scope.myInfo.elastic_apm_server_url
      , serviceVersion: $scope.myInfo.elastic_apm_version
      , environment: $scope.myInfo.elastic_apm_environment
      , active: true
      , instrument: true
      , apiVersion: 2
      , breakdownMetrics: true
      , pageLoadTransactionName: pageName
      , pageLoadTraceId: $scope.myInfo.elastic_apm_transaction_trace_id
      , pageLoadSpanId: $scope.myInfo.elastic_apm_transaction_id
      , pageLoadSampled: $scope.myInfo.elastic_apm_transaction_sampled
    }
)
```

but `$scope.myInfo.elastic_apm_transaction_sampled` was set to evaluate to a string "t" or "f" as instructed by the error. However, it must be a boolean (so `true` or `false`). That solved it.
