### ISSUE TITLE
figure out why e2e tests fails occasionally on chrome 49

### ISSUE THREAD

**Issue by vigneshshanmugam** [elastic/apm-agent-rum-js#240]
The E2E general-usecase tests has some race condition when running on chrome 49. Probably its a browser bug, but we need to find out why it happens occasionally. 

Example travis job. - https://travis-ci.org/elastic/apm-agent-rum-js/jobs/512143864

```
[test:e2e:supported] [chrome 49 #0-0] Running: chrome (v49)
[test:e2e:supported] [chrome 49 #0-0]
[test:e2e:supported] [chrome 49 #0-0] general-usercase
[test:e2e:supported] [chrome 49 #0-0]    ✖ should run the general usecase
[test:e2e:supported] [chrome 49 #0-0]
[test:e2e:supported] [chrome 49 #0-0] 1 failing (3.4s)
[test:e2e:supported] [chrome 49 #0-0]
[test:e2e:supported] [chrome 49 #0-0] 1) general-usercase should run the general usecase
[test:e2e:supported] [chrome 49 #0-0] Expected 2 to be greater than 2.
[test:e2e:supported] [chrome 49 #0-0] Error: Expected 2 to be greater than 2.
[test:e2e:supported] [chrome 49 #0-0]     at <Jasmine>
[test:e2e:supported] [chrome 49 #0-0]     at UserContext.<anonymous> (/home/travis/build/elastic/apm-agent-rum-js/packages/rum/test/e2e/general-usecase/app.e2e-spec.js:105:45)
[test:e2e:supported] [chrome 49 #0-0]     at <Jasmine>
[test:e2e:supported] [chrome 49 #0-0] Expected undefined to be defined.
[test:e2e:supported] [chrome 49 #0-0] Error: Expected undefined to be defined.
[test:e2e:supported] [chrome 49 #0-0]     at <Jasmine>
[test:e2e:supported] [chrome 49 #0-0]     at UserContext.<anonymous> (/home/travis/build/elastic/apm-agent-rum-js/packages/rum/test/e2e/general-usecase/app.e2e-spec.js:109:18)
[test:e2e:supported] [chrome 49 #0-0]     at <Jasmine>
[test:e2e:supported] [chrome 49 #0-0]
[test:e2e:supported] [chrome 49 #0-0] Check out job at https://app.saucelabs.com/tests/bdb6fcb9d0744d3d92d6bb0e214f3e5d

```

**Comment by jahtalab** [comment]
Investigated a little bit:


In a normal run the transaction payload should look like this:
```
{
    "sendTransactions": [
        {
            "mocked": false,
            "args": [
                [
                    {
                        "sampled": true,
                        "spans": [
                            {
                                "name": "Requesting and receiving the document",
                                "start": 1177,
                                "trace_id": "286ac3ad697892c406528f13c82e0ce1",
                                "parent_id": "c9f102710288e63d",
                                "subType": "browser-timing",
                                "duration": 150,
                                "type": "hard-navigation",
                                "id": "bbd8bcc3be14d814",
                                "transaction_id": "c9f102710288e63d"
                            },
                            {
                                "name": "http://localhost:8000/test/e2e/general-usecase/app.e2e-bundle.min.js",
                                "start": 1334.13121,
                                "trace_id": "286ac3ad697892c406528f13c82e0ce1",
                                "parent_id": "c9f102710288e63d",
                                "subType": "script",
                                "context": {
                                    "http": {
                                        "url": "http://localhost:8000/test/e2e/general-usecase/app.e2e-bundle.min.js?token=secret"
                                    }
                                },
                                "duration": 117.94671,
                                "type": "resource",
                                "id": "44c0f03bc6c43824",
                                "transaction_id": "c9f102710288e63d"
                            },
                            {
                                "name": "OpenTracing span",
                                "start": 1500.57911,
                                "trace_id": "286ac3ad697892c406528f13c82e0ce1",
                                "parent_id": "c9f102710288e63d",
                                "duration": 199.42089,
                                "type": "custom",
                                "id": "c651fe01da93282c",
                                "transaction_id": "c9f102710288e63d"
                            },
                            {
                                "name": "GET /test/e2e/common/data.json",
                                "start": 1505.13911,
                                "trace_id": "286ac3ad697892c406528f13c82e0ce1",
                                "sync": true,
                                "parent_id": "c9f102710288e63d",
                                "subType": "http",
                                "context": {
                                    "http": {
                                        "url": "/test/e2e/common/data.json?test=hamid",
                                        "status_code": 200,
                                        "method": "GET"
                                    }
                                },
                                "duration": 102.815,
                                "type": "external",
                                "id": "f8d812978c9e7063",
                                "transaction_id": "c9f102710288e63d"
                            },
                            {
                                "name": "POST http://localhost:8003/data",
                                "start": 1608.69411,
                                "trace_id": "286ac3ad697892c406528f13c82e0ce1",
                                "sync": true,
                                "parent_id": "c9f102710288e63d",
                                "subType": "http",
                                "context": {
                                    "http": {
                                        "url": "http://localhost:8003/data",
                                        "status_code": 200,
                                        "method": "POST"
                                    }
                                },
                                "duration": 91.30589,
                                "type": "external.truncated",
                                "id": "d55ccaa706d0989f",
                                "transaction_id": "c9f102710288e63d"
                            }
                        ],
                        "trace_id": "286ac3ad697892c406528f13c82e0ce1",
                        "span_count": {
                            "started": 5
                        },
                        "context": {
                            "custom": {
                                "testContext": "testContext"
                            },
                            "page": {
                                "url": "http://localhost:8000/test/e2e/general-usecase/index.html",
                                "referer": ""
                            },
                            "tags": {
                                "testTagKey": "testTagValue"
                            },
                            "user": {
                                "username": "username",
                                "id": "userId",
                                "email": "email"
                            }
                        },
                        "marks": {
                            "navigationTiming": {
                                "domContentLoadedEventStart": 2015,
                                "fetchStart": 0,
                                "loadEventEnd": 2018,
                                "domainLookupEnd": 0,
                                "connectEnd": 0,
                                "requestStart": 1177,
                                "responseEnd": 1327,
                                "domLoading": 1324,
                                "connectStart": 0,
                                "loadEventStart": 2017,
                                "domComplete": 2017,
                                "domContentLoadedEventEnd": 2015,
                                "responseStart": 1324,
                                "domInteractive": 2015,
                                "domainLookupStart": 0
                            },
                            "agent": {
                                "domComplete": 2017,
                                "timeToFirstByte": 1324,
                                "domInteractive": 2015
                            }
                        },
                        "duration": 1700,
                        "type": "page-load",
                        "id": "c9f102710288e63d",
                        "name": "general-usecase-initial-page-load"
                    }
                ]
            ]
        }
    ]
}
```

However, in failures there are number of standard spans missing:
```
{
    "sendTransactions": [
        {
            "mocked": false,
            "args": [
                [
                    {
                        "sampled": true,
                        "spans": [
                            {
                                "name": "Requesting and receiving the document",
                                "subType": "browser-timing",
                                "trace_id": "286ac3ad697892c406528f13c82e0ce1",
                                "start": 18,
                                "parent_id": "ea87453b153bf915",
                                "duration": 272,
                                "type": "hard-navigation",
                                "id": "bbd8bcc3be14d814",
                                "transaction_id": "ea87453b153bf915"
                            },
                            {
                                "name": "http://localhost:8000/test/e2e/general-usecase/app.e2e-bundle.min.js",
                                "start": 549.995,
                                "trace_id": "286ac3ad697892c406528f13c82e0ce1",
                                "parent_id": "ea87453b153bf915",
                                "subType": "script",
                                "context": {
                                    "http": {
                                        "url": "http://localhost:8000/test/e2e/general-usecase/app.e2e-bundle.min.js?token=secret"
                                    }
                                },
                                "duration": 103,
                                "type": "resource",
                                "id": "7e16580007decf3b",
                                "transaction_id": "ea87453b153bf915"
                            }
                        ],
                        "name": "general-usecase-initial-page-load",
                        "trace_id": "286ac3ad697892c406528f13c82e0ce1",
                        "span_count": {
                            "started": 2
                        },
                        "context": {
                            "user": {
                                "username": "username",
                                "email": "email",
                                "id": "userId"
                            },
                            "tags": {
                                "testTagKey": "testTagValue"
                            },
                            "page": {
                                "url": "http://localhost:8000/test/e2e/general-usecase/index.html",
                                "referer": ""
                            },
                            "custom": {
                                "testContext": "testContext"
                            }
                        },
                        "marks": {
                            "navigationTiming": {
                                "domContentLoadedEventStart": 732,
                                "responseEnd": 290,
                                "loadEventStart": 733,
                                "domainLookupEnd": 0,
                                "connectEnd": 0,
                                "requestStart": 18,
                                "loadEventEnd": 733,
                                "domLoading": 292,
                                "domInteractive": 732,
                                "fetchStart": 0,
                                "domComplete": 733,
                                "domContentLoadedEventEnd": 732,
                                "responseStart": 290,
                                "connectStart": 0,
                                "domainLookupStart": 0
                            },
                            "agent": {
                                "domComplete": 733,
                                "timeToFirstByte": 290,
                                "domInteractive": 732
                            }
                        },
                        "duration": 692,
                        "type": "page-load",
                        "id": "ea87453b153bf915"
                    }
                ]
            ]
        }
    ]
}
```
