### ISSUE TITLE
Request header field authorization is not allowed by Access-Control-Allow-Headers in preflight response

### ISSUE THREAD

**Issue by WassimDhib** [elastic/apm-agent-rum-js#331]
Hi,  

I have an application with rum-gent installed.

rum-agent  works fine with regular browser.

Now, when using a headless browser (puppeteer/chromium), I have this issue when connecting to a specific page behind a basic http authentification.  ( It works fine for no auth pages  )

```
  puppeteer:protocol -> RECV {"method":"Network.requestWillBeSent","params":{"requestId":"1000032693.6","loaderId":"779C8F9CA8545001DF612D18D958AF4D","documentURL":"http://localhost:8080/jpetstore/","request":{"url":"http://localhost:8200/intake/v2/rum/events","method":"POST","headers":{"Sec-Fetch-Mode":"cors","Referer":"http://localhost:8080/jpetstore/","authorization":"Basic ajJlZTpqMmVl","User-Agent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/77.0.3835.0 Safari/537.36","Content-Type":"application/x-ndjson"},"postData":"{\"metadata\":{\"service\":{\"name\":\"jpetstore\",\"agent\":{\"name\":\"js-base\",\"version\":\"4.3.0\"},\"language\":{\"name\":\"javascript\"}}}}\n{\"transaction\":{\"id\":\"b91a7582949a3442\",\"trace_id\":\"c4632b322e0b7d6dc5833bb466e0d9c7\",\"name\":\"main-page\",\"type\":\"page-load\",\"duration\":47.75499925017357,\"context\":{\"page\":{\"referer\":\"\",\"url\":\"http://localhost:8080/jpetstore/\"}},\"marks\":{\"navigationTiming\":{\"fetchStart\":0,\"domainLookupStart\":6,\"domainLookupEnd\":6,\"connectStart\":6,\"connectEnd\":7,\"requestStart\":7,\"responseStart\":8,\"responseEnd\":9,\"domLoading\":14,\"domInteractive\":32,\"domContentLoadedEventStart\":32,\"domContentLoadedEventEnd\":32,\"domComplete\":42,\"loadEventStart\":42,\"loadEventEnd\":42},\"agent\":{\"timeToFirstByte\":8,\"domInteractive\":32,\"domComplete\":42}},\"span_count\":{\"started\":5},\"sampled\":true}}\n{\"span\":{\"id\":\"7ee33fbf2d3eef72\",\"transaction_id\":\"b91a7582949a3442\",\"parent_id\":\"b91a7582949a3442\",\"trace_id\":\"c4632b322e0b7d6dc5833bb466e0d9c7\",\"name\":\"Making a connection to the server\",\"type\":\"hard-navigation\",\"subType\":\"browser-timing\",\"start\":6,\"duration\":1}}\n{\"span\":{\"id\":\"b1b843cbe66f4c2c\",\"transaction_id\":\"b91a7582949a3442\",\"parent_id\":\"b91a7582949a3442\",\"trace_id\":\"c4632b322e0b7d6dc5833bb466e0d9c7\",\"name\":\"Requesting and receiving the document\",\"type\":\"hard-navigation\",\"subType\":\"browser-timing\",\"start\":7,\"duration\":2}}\n{\"span\":{\"id\":\"3fdb637bbeb3f04e\",\"transaction_id\":\"b91a7582949a3442\",\"parent_id\":\"b91a7582949a3442\",\"trace_id\":\"c4632b322e0b7d6dc5833bb466e0d9c7\",\"name\":\"Parsing the document, executing sync. scripts\",\"type\":\"hard-navigation\",\"subType\":\"browser-timing\",\"start\":14,\"duration\":18}}\n{\"span\":{\"id\":\"aacb90fee7b4e090\",\"transaction_id\":\"b91a7582949a3442\",\"parent_id\":\"b91a7582949a3442\",\"trace_id\":\"c4632b322e0b7d6dc5833bb466e0d9c7\",\"name\":\"http://localhost:8080/jpetstore/dist/bundles/elastic-apm-rum.umd.min.js\",\"type\":\"resource\",\"subType\":\"script\",\"start\":16.974998638033867,\"duration\":2.940000966191292,\"context\":{\"http\":{\"url\":\"http://localhost:8080/jpetstore/dist/bundles/elastic-apm-rum.umd.min.js\"}}}}\n{\"span\":{\"id\":\"50388ea680eed1a7\",\"transaction_id\":\"b91a7582949a3442\",\"parent_id\":\"b91a7582949a3442\",\"trace_id\":\"c4632b322e0b7d6dc5833bb466e0d9c7\",\"name\":\"http://localhost:8080/jpetstore/css/jpetstore.css\",\"type\":\"resource\",\"subType\":\"link\",\"start\":17.184998840093613,\"duration\":4.045000299811363,\"context\":{\"http\":{\"url\":\"http://localhost:8080/jpetstore/css/jpetstore.css\"}}}}\n","hasPostData":true,"mixedContentType":"none","initialPriority":"High","referrerPolicy":"no-referrer-when-downgrade"},"timestamp":14017117.97117,"wallTime":1563287106.652057,"initiator":{"type":"script","stack":{"callFrames":[{"functionName":"","scriptId":"12","url":"http://localhost:8080/jpetstore/dist/bundles/elastic-apm-rum.umd.min.js","lineNumber":1,"columnNumber":18810},{"functionName":"","scriptId":"12","url":"http://localhost:8080/jpetstore/dist/bundles/elastic-apm-rum.umd.min.js","lineNumber":1,"columnNumber":18857},{"functionName":"U.r.<computed>","scriptId":"12","url":"http://localhost:8080/jpetstore/dist/bundles/elastic-apm-rum.umd.min.js","lineNumber":1,"columnNumber":17634},{"functionName":"","scriptId":"12","url":"http://localhost:8080/jpetstore/dist/bundles/elastic-apm-rum.umd.min.js","lineNumber":1,"columnNumber":40797},{"functionName":"e._makeHttpRequest","scriptId":"12","url":"http://localhost:8080/jpetstore/dist/bundles/elastic-apm-rum.umd.min.js","lineNumber":1,"columnNumber":40436},{"functionName":"e._postJson","scriptId":"12","url":"http://localhost:8080/jpetstore/dist/bundles/elastic-apm-rum.umd.min.js","lineNumber":1,"columnNumber":40322},{"functionName":"e._send","scriptId":"12","url":"http://localhost:8080/jpetstore/dist/bundles/elastic-apm-rum.umd.min.js","lineNumber":1,"columnNumber":42968},{"functionName":"e.sendTransactions","scriptId":"12","url":"http://localhost:8080/jpetstore/dist/bundles/elastic-apm-rum.umd.min.js","lineNumber":1,"columnNumber":43091},{"functionName":"","scriptId":"12","url":"http://localhost:8080/jpetstore/dist/bundles/elastic-apm-rum.umd.min.js","lineNumber":1,"columnNumber":41619},{"functionName":"e.flush","scriptId":"12","url":"http://localhost:8080/jpetstore/dist/bundles/elastic-apm-rum.umd.min.js","lineNumber":1,"columnNumber":38942},{"functionName":"","scriptId":"12","url":"http://localhost:8080/jpetstore/dist/bundles/elastic-apm-rum.umd.min.js","lineNumber":1,"columnNumber":38888}]}},"type":"XHR","frameId":"9EF86A5665246D09409BFA35E473CF02","hasUserGesture":false},"sessionId":"65BA31DBD09DD8E019C1FF4103F5AAD4"} +496ms
  
  puppeteer:protocol -> RECV {"method":"Log.entryAdded","params":{"entry":{"source":"javascript","level":"error","text":"Access to XMLHttpRequest at 'http://localhost:8200/intake/v2/rum/events' from origin 'http://localhost:8080' has been blocked by CORS policy: Request header field authorization is not allowed by Access-Control-Allow-Headers in preflight response.","timestamp":1563287106654.223,"url":"http://localhost:8080/jpetstore/"}},"sessionId":"65BA31DBD09DD8E019C1FF4103F5AAD4"} +2ms
  
  puppeteer:protocol -> RECV {"method":"Runtime.consoleAPICalled","params":{"type":"warning","args":[{"type":"string","value":"Failed sending transactions!"},{"type":"object","subtype":"error","className":"Error","description":"Error: http://localhost:8200/intake/v2/rum/events HTTP status: 0\n    at XMLHttpRequest.i.onreadystatechange (http://localhost:8080/jpetstore/dist/bundles/elastic-apm-rum.umd.min.js:2:40698)","objectId":"{\"injectedScriptId\":3,\"id\":1}","preview":{"type":"object","subtype":"error","description":"Error: http://localhost:8200/intake/v2/rum/events HTTP status: 0\n    at XMLHttpRequest.i.onreadystatechange (http://localhost:8080/jpetstore/dist/bundles/elastic-apm-rum.umd.min.js:2:40698)","overflow":false,"properties":[{"name":"xhr","type":"object","value":"XMLHttpRequest"},{"name":"stack","type":"string","value":"Error: http://localhost:8200/intake/v2/rum/events \u2026/dist/bundles/elastic-apm-rum.umd.min.js:2:40698)"},{"name":"message","type":"string","value":"http://localhost:8200/intake/v2/rum/events HTTP status: 0"}]}}],"executionContextId":3,"timestamp":1563287106654.5469,"stackTrace":{"callFrames":[{"functionName":"o.<computed>","scriptId":"12","url":"http://localhost:8080/jpetstore/dist/bundles/elastic-apm-rum.umd.min.js","lineNumber":1,"columnNumber":46874},{"functionName":"","scriptId":"12","url":"http://localhost:8080/jpetstore/dist/bundles/elastic-apm-rum.umd.min.js","lineNumber":1,"columnNumber":41686}]}},"sessionId":"65BA31DBD09DD8E019C1FF4103F5AAD4"} +0ms
  
  puppeteer:protocol SEND -> {"sessionId":"65BA31DBD09DD8E019C1FF4103F5AAD4","method":"Runtime.releaseObject","params":{"objectId":"{\"injectedScriptId\":3,\"id\":1}"},"id":21} +1ms
```

**Comment by jahtalab** [comment]
Hi @WassimDhib ,

Are you running your APM server behind an authentication proxy as well or is it just the server that is serving the page?
Would you please provide the export in HAR format for both preflieght (OPTIONS) and POST request if possible?

**Comment by WassimDhib** [comment]
Hi @jahtalab 
The APM server is not behind a proxy.

I'm not very familiar with chromium, I'll try to get ther HAR. 
I'll keep you informed

**Comment by vigneshshanmugam** [comment]
Closing due to inactivity. Please let us know if you still see any issues.
