### ISSUE TITLE
Getting Error on building `apm-rum-react`

### ISSUE THREAD

**Issue by sahil-bansal-sb** [elastic/apm-agent-rum-js#347]
I tried to use `@elastic/apm-rum-react` repo and Implement APM agent with the route by using `ApmRoute`, I just imported and saved the package, which is throwing the following error:

```
ERROR in ./node_modules/@elastic/apm-rum-react/src/get-apm-route.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: ./node_modules/@elastic/apm-rum-react/src/get-apm-route.js: Unexpected token (39:13)

  37 |     }
  38 |     render() {
> 39 |       return <Route {...this.props} component={this.ApmComponent} />
     |              ^
  40 |     }
  41 |   }
  42 | }
    at Parser.raise (./node_modules/@babel/parser/lib/index.js:3831:17)
    at Parser.unexpected (./node_modules/@babel/parser/lib/index.js:5143:16)
    at Parser.parseExprAtom (./node_modules/@babel/parser/lib/index.js:6283:20)
    at Parser.parseExprSubscripts (./node_modules/@babel/parser/lib/index.js:5862:23)
    at Parser.parseMaybeUnary (./node_modules/@babel/parser/lib/index.js:5842:21)
    at Parser.parseExprOps (./node_modules/@babel/parser/lib/index.js:5729:23)
    at Parser.parseMaybeConditional (./node_modules/@babel/parser/lib/index.js:5702:23)
    at Parser.parseMaybeAssign (./node_modules/@babel/parser/lib/index.js:5647:21)
    at Parser.parseExpression (./node_modules/@babel/parser/lib/index.js:5595:23)
    at Parser.parseReturnStatement (./node_modules/@babel/parser/lib/index.js:7617:28)
 @ ./node_modules/@elastic/apm-rum-react/src/index.js 27:0-46 29:17-28
 @ ./src/routes/Route.js
 @ ./src/index.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 (webpack)/hot/dev-server.js ./src/index.js

ERROR in ./node_modules/@elastic/apm-rum-react/src/get-with-transaction.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: ./node_modules/@elastic/apm-rum-react/src/get-with-transaction.js: Unexpected token (69:12)

  67 |           // todo: should we pass the transaction down (could use react context provider instead)
  68 |           return (
> 69 |             <WrappedComponent transaction={this.transaction} {...this.props} />
     |             ^
  70 |           )
  71 |         }
  72 |       }
    at Parser.raise (./node_modules/@babel/parser/lib/index.js:3831:17)
    at Parser.unexpected (./node_modules/@babel/parser/lib/index.js:5143:16)
    at Parser.parseExprAtom (./node_modules/@babel/parser/lib/index.js:6283:20)
    at Parser.parseExprSubscripts (./node_modules/@babel/parser/lib/index.js:5862:23)
    at Parser.parseMaybeUnary (./node_modules/@babel/parser/lib/index.js:5842:21)
    at Parser.parseExprOps (./node_modules/@babel/parser/lib/index.js:5729:23)
    at Parser.parseMaybeConditional (./node_modules/@babel/parser/lib/index.js:5702:23)
    at Parser.parseMaybeAssign (./node_modules/@babel/parser/lib/index.js:5647:21)
    at Parser.parseParenAndDistinguishExpression (./node_modules/@babel/parser/lib/index.js:6435:28)
    at Parser.parseExprAtom (./node_modules/@babel/parser/lib/index.js:6215:21)
 @ ./node_modules/@elastic/apm-rum-react/src/index.js 26:0-60 28:24-42
 @ ./src/routes/Route.js
 @ ./src/index.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 (webpack)/hot/dev-server.js ./src/index.js
```

I have used the following rule for loading the package,
```
    {
        test: /\.(js|jsx)$/,
        include: /@elastic/,
        loader: 'babel-loader'
    },
``` 

Version:
``` 
webpack 4.29.6


"babel-loader": "^8.0.4",
```

**Comment by vigneshshanmugam** [comment]
@sahil-bansal-sb Thanks for trying out the react integration. You have to add `@babel/react` preset to your babel config inorder to parse JSX elements. https://babeljs.io/docs/en/babel-preset-react

Let us know if you run in to any issues.

**Comment by sahil-bansal-sb** [comment]
I am already using it,

.babelrc:
```
{
    "presets": [
        "@babel/preset-react",
        [
            "@babel/preset-env",
            {
                "useBuiltIns": "entry"
            }
        ]
        
    ],
    "plugins": [
        "@babel/plugin-proposal-object-rest-spread",
        "@babel/plugin-transform-runtime",
        "@babel/plugin-transform-async-to-generator",
        "@babel/plugin-proposal-class-properties"
    ]
}
```

devDependencies:
```
    "@babel/core": "^7.3.3",
    "@babel/plugin-proposal-class-properties": "^7.3.0",
    "@babel/plugin-proposal-object-rest-spread": "^7.3.1",
    "@babel/plugin-transform-async-to-generator": "^7.2.0",
    "@babel/plugin-transform-runtime": "^7.2.0",
    "@babel/preset-env": "^7.3.1",
    "@babel/preset-react": "^7.0.0",
    ....
```

**Comment by sahil-bansal-sb** [comment]
I am also using JSX syntax for my other components and routes,
it is working fine for them.

**Comment by vigneshshanmugam** [comment]
Interesting. Can you give me link to a minimal repro?

**Comment by Stetchy** [comment]
Also having this issue - I think it is an issue with the configs in this package, putting the same files directly into your project works fine. I don't think Babel is configured correctly for JSX/React.

**Comment by sahil-bansal-sb** [comment]
https://github.com/sahil-bansal-sb/minimal-react-repo

Please Refer src/routes/Route.js

**Comment by sahil-bansal-sb** [comment]
> Also having this issue - I think it is an issue with the configs in this package, putting the same files directly into your project works fine. I don't think Babel is configured correctly for JSX/React.

tried this too, not working for me

**Comment by sahil-bansal-sb** [comment]
> > Also having this issue - I think it is an issue with the configs in this package, putting the same files directly into your project works fine. I don't think Babel is configured correctly for JSX/React.
> 
> tried this too, not working for me

done, i was importing from src of all dirs

**Comment by vigneshshanmugam** [comment]
@sahil-bansal-sb Thanks for providing the repo. 

The `.babelrc` file is in the wrong path that is why the transformation is not happening on the `@elastic/apm-rum-react`. You can confirm it by hardcoding it on the babel-loader options. 
```js
{
        test: /\.(js|jsx)$/,
        include: [src, path.join(paths.root, 'node_modules', '@elastic')],
        loader: 'babel-loader',
        options: {
            presets: [
                '@babel/preset-react',
                [
                    '@babel/preset-env',
                    {
                        useBuiltIns: 'entry'
                    }
                ]
            ],
            plugins: [
                '@babel/plugin-proposal-object-rest-spread',
                '@babel/plugin-transform-runtime',
                '@babel/plugin-transform-async-to-generator',
                '@babel/plugin-proposal-class-properties'
            ]
        }
    },

```

**Comment by vigneshshanmugam** [comment]
@Stetchy We expose the package in two ways - CJS and source code with ES6 Modules(without any transpilation) 
```
{
  "main": "dist/lib/index.js",
  "module": "src/index.js"
}
``

If you use ES6 aware bundler like webpack etc. The bundlers will try to resolve the file through `module` field because you can yield better bundlesize due to treeshaking and DCE features of the bundler. 

Since now you are dealing with untraspiled code, the options must include appropriate loaders and config to handle them.

**Comment by sahil-bansal-sb** [comment]
> @sahil-bansal-sb Thanks for providing the repo.
> 
> The `.babelrc` file is in the wrong path that is why the transformation is not happening on the `@elastic/apm-rum-react`. You can confirm it by hardcoding it on the babel-loader options.
> 
> ```js
> {
>         test: /\.(js|jsx)$/,
>         include: [src, path.join(paths.root, 'node_modules', '@elastic')],
>         loader: 'babel-loader',
>         options: {
>             presets: [
>                 '@babel/preset-react',
>                 [
>                     '@babel/preset-env',
>                     {
>                         useBuiltIns: 'entry'
>                     }
>                 ]
>             ],
>             plugins: [
>                 '@babel/plugin-proposal-object-rest-spread',
>                 '@babel/plugin-transform-runtime',
>                 '@babel/plugin-transform-async-to-generator',
>                 '@babel/plugin-proposal-class-properties'
>             ]
>         }
>     },
> ```
> 
> You can learn more about how babel configs are picked up here - https://babeljs.io/docs/en/configuration#what-s-your-use-case

worked great, thanks

but if someone is working with react-scripts directly, how should we do it

**Comment by sahil-bansal-sb** [comment]
In some other project, i'm using the react-scripts
whose package.json is something like:
```
{
  "dependencies": {
    ...
    "@elastic/apm-rum": "^4.3.1",
    "@elastic/apm-rum-core": "^4.4.0",
    "@elastic/apm-rum-react": "^0.1.1",
    "es6-symbol": "^3.1.1",
    "react": "^16.8.6",
    "react-dom": "^16.8.6",
    "react-redux": "^6.0.0",
    "react-router-dom": "^4.3.1",
    "react-router-redux": "^4.0.8",
    "react-scripts": "2.1.8",
    "redux": "^4.0.1",
    "redux-thunk": "^2.3.0",
    "webpack": "^4.0.0-beta.1",
    "webpack-cli": "^2.0.6",
    "webpack-dev-server": "^3.0.0-beta.1",
    ...
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject",
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "devDependencies": {
    "@babel/core": "^7.3.3",
    "@babel/plugin-proposal-class-properties": "^7.3.0",
    "@babel/plugin-proposal-object-rest-spread": "^7.3.1",
    "@babel/plugin-transform-async-to-generator": "^7.2.0",
    "@babel/plugin-transform-runtime": "^7.2.0",
    "@babel/preset-env": "^7.3.1",
    "@babel/preset-react": "^7.0.0",
    "mini-css-extract-plugin": "^0.6.0"
  },
  "babel": {
    "presets": [
      "@babel/preset-react",
      [
        "@babel/preset-env",
        {
          "useBuiltIns": "entry"
        }
      ]
    ],
    "plugins": [
      "@babel/plugin-proposal-object-rest-spread",
      "@babel/plugin-transform-runtime",
      "@babel/plugin-transform-async-to-generator",
      "@babel/plugin-proposal-class-properties"
    ]
  }
}
```

As you can see i tried to put babel config in `package.json`
but got the same error as before

```
Failed to compile.

./node_modules/@elastic/apm-rum-react/src/get-apm-route.js
SyntaxError: ./node_modules/@elastic/apm-rum-react/src/get-apm-route.js: Unexpected token (37:13)

  35 |       const { path, component } = this.props
  36 |       const apmComponent = withTransaction(path, 'route-change')(component)
> 37 |       return <Route {...this.props} component={apmComponent} />
     |              ^
  38 |     }
  39 |   }
  40 | }
```

**Comment by sahil-bansal-sb** [comment]
I also tried to put the same babel config in babel.config.js, put it in the parent dir of package.json as suggested by [https://new.babeljs.io/docs/en/next/babelconfigjs.html#merging-behavior](https://new.babeljs.io/docs/en/next/babelconfigjs.html#merging-behavior) and I think it should work on the project dependencies

**Comment by vigneshshanmugam** [comment]
Yes babel.config.js works in your case. For create-react-app, you can eject the webpack config and add `@elastic/apm-rum` to the babel loader `include` config. If you dont want to do that, you can import the package dist instead. 

```js
import { ApmRoute } from "@elastic/apm-rum-react/dist/lib"
```

**Comment by sahil-bansal-sb** [comment]
Thanks a lot.
