### ISSUE TITLE
create new build targets compatible with Angular Packaging Format

### ISSUE THREAD

**Issue by vigneshshanmugam** [elastic/apm-agent-rum-js#607]
+ Currently we expose `elastic/apm-rum-angular` with default target `IE11` which transpiles the native ES6 classes to ES5 compatible versions. When used in Angular projects bootstrapped with Angular CLI, the default target is `es2015/es6` and our `ApmErrorHandler` plugin wont work since native class is not compatible with transpiled one. 

```
Unhandled Promise rejection: Class constructor ErrorHandler cannot be invoked without 'new' ; Zone: <root> ; Task: Promise.then ; Value: TypeError: Class constructor ErrorHandler cannot be invoked without 'new'
    at new ApmErrorHandler (error-handler.js:8)
    at _createClass (core.js:30459)
    at _createProviderInstance (core.js:30426)
    at initNgModule (core.js:30332)
    at new NgModuleRef_ (core.js:31561)
    at createNgModuleRef (core.js:31544)
    at Object.debugCreateNgModuleRef [as createNgModuleRef] (core.js:44911)
    at NgModuleFactory_.create (core.js:46088)
    at core.js:40535
    at ZoneDelegate.invoke (zone-evergreen.js:359) TypeError: Class constructor ErrorHandler cannot be invoked without 'new'
    at new ApmErrorHandler (http://localhost:4200/vendor.js:108489:26)
    at _createClass (http://localhost:4200/vendor.js:71894:20)
    at _createProviderInstance (http://localhost:4200/vendor.js:71861:26)
    at initNgModule (http://localhost:4200/vendor.js:71767:32)
    at new NgModuleRef_ (http://localhost:4200/vendor.js:72877:9)
    at createNgModuleRef (http://localhost:4200/vendor.js:72860:12)
    at Object.debugCreateNgModuleRef [as createNgModuleRef] (http://localhost:4200/vendor.js:85070:12)
    at NgModuleFactory_.create (http://localhost:4200/vendor.js:86203:25)
    at http://localhost:4200/vendor.js:80903:64
    at ZoneDelegate.invoke (http://localhost:4200/polyfills.js:6074:26)
```

Easiest way to fix the problem is to add two new build targets, one for `es5` and one for `es6` depending on the [Angular Packaging Format](https://docs.google.com/document/d/1CZC2rcpxffTDfRDs6p1cfbmKNLA6x5O-NtkJglDaBVs/preview)

More details on this issue #603

**Comment by icecoldfire** [comment]
When will this issue be resolved?

**Comment by chriscarpenter12** [comment]
I agree. We can't expect everyone to change their targets to `es5` and abandon differential loading in Angular 8+.
